In [71]:
## Import Libaries

import numpy as np
import pandas as pd
import string
import nltk
import re
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from nltk.stem import WordNetLemmatizer
from sklearn.model_selection import train_test_split

In [72]:
lm = WordNetLemmatizer()

In [73]:
## Stop words
sw = stopwords.words('english')

In [74]:
## Reading the positive data
pos_rev = pd.read_csv(r'C:\Users\Darshana\Desktop\DSC_WKND20092020\NLP\netflix\pos.txt',header=None,sep='\n',encoding='latin-1')
pos_rev

0
0     the rock is destined to be the 21st century's ...
1     the gorgeously elaborate continuation of " the...
2                        effective but too-tepid biopic
3     if you sometimes like to go to the movies to h...
4     emerges as something rare , an issue movie tha...
...                                                 ...
5326  both exuberantly romantic and serenely melanch...
5327  mazel tov to a film about a family's joyous li...
5328  standing in the shadows of motown is the best ...
5329  it's nice to see piscopo again after all these...
5330  provides a porthole into that noble , tremblin...

[5331 rows x 1 columns]

In [75]:
## Creating Target Column & renaming the column
pos_rev['mood'] = 1.0
pos_rev = pos_rev.rename(columns={0:'review'})
pos_rev

review  mood
0     the rock is destined to be the 21st century's ...   1.0
1     the gorgeously elaborate continuation of " the...   1.0
2                        effective but too-tepid biopic   1.0
3     if you sometimes like to go to the movies to h...   1.0
4     emerges as something rare , an issue movie tha...   1.0
...                                                 ...   ...
5326  both exuberantly romantic and serenely melanch...   1.0
5327  mazel tov to a film about a family's joyous li...   1.0
5328  standing in the shadows of motown is the best ...   1.0
5329  it's nice to see piscopo again after all these...   1.0
5330  provides a porthole into that noble , tremblin...   1.0

[5331 rows x 2 columns]

In [76]:
## Reading the negative data
neg_rev = pd.read_csv(r'C:\Users\Darshana\Desktop\DSC_WKND20092020\NLP\netflix\negative.txt',header=None,sep='\n',encoding='latin-1')

## Creating Target Column & renaming the column
neg_rev['mood'] = 0.0
neg_rev = neg_rev.rename(columns={0:'review'})
neg_rev

review  mood
0                      simplistic , silly and tedious.    0.0
1     it's so laddish and juvenile , only teenage bo...   0.0
2     exploitative and largely devoid of the depth o...   0.0
3     [garbus] discards the potential for pathologic...   0.0
4     a visually flashy but narratively opaque and e...   0.0
...                                                 ...   ...
5326  a terrible movie that some people will neverth...   0.0
5327  there are many definitions of 'time waster' bu...   0.0
5328  as it stands , crocodile hunter has the hurrie...   0.0
5329  the thing looks like a made-for-home-video qui...   0.0
5330  enigma is well-made , but it's just too dry an...   0.0

[5331 rows x 2 columns]

In [77]:
pos_rev.loc[:,'review'] = pos_rev.loc[:,'review'].apply(lambda x:x.lower())
pos_rev.loc[:,'review'] = pos_rev.loc[:,'review'].apply(lambda x:re.sub(r'@\S+','',x))
pos_rev.loc[:,'review'] = pos_rev.loc[:,'review'].apply(lambda x:x.translate(str.maketrans(dict.fromkeys((string.punctuation)))))
pos_rev.loc[:,'review'] = pos_rev.loc[:,'review'].apply(lambda x: " ".join([word for word in x.split() if word not in (sw)]))
pos_rev.loc[:,'review'] = pos_rev.loc[:,'review'].apply(lambda x:" ".join([lm.lemmatize(word,pos='v') for word in x.split()]))
pos_rev.loc[:,'review']

0       rock destine 21st centurys new conan hes go ma...
1       gorgeously elaborate continuation lord ring tr...
2                               effective tootepid biopic
3       sometimes like go movies fun wasabi good place...
4       emerge something rare issue movie thats honest...
                              ...                        
5326    exuberantly romantic serenely melancholy time ...
5327    mazel tov film familys joyous life act yiddish...
5328    stand shadow motown best kind documentary one ...
5329      nice see piscopo years chaykin headly priceless
5330    provide porthole noble tremble incoherence def...
Name: review, Length: 5331, dtype: object

In [78]:
neg_rev.loc[:,'review'] = neg_rev.loc[:,'review'].apply(lambda x:x.upper())
neg_rev.loc[:,'review']

0                        SIMPLISTIC , SILLY AND TEDIOUS. 
1       IT'S SO LADDISH AND JUVENILE , ONLY TEENAGE BO...
2       EXPLOITATIVE AND LARGELY DEVOID OF THE DEPTH O...
3       [GARBUS] DISCARDS THE POTENTIAL FOR PATHOLOGIC...
4       A VISUALLY FLASHY BUT NARRATIVELY OPAQUE AND E...
                              ...                        
5326    A TERRIBLE MOVIE THAT SOME PEOPLE WILL NEVERTH...
5327    THERE ARE MANY DEFINITIONS OF 'TIME WASTER' BU...
5328    AS IT STANDS , CROCODILE HUNTER HAS THE HURRIE...
5329    THE THING LOOKS LIKE A MADE-FOR-HOME-VIDEO QUI...
5330    ENIGMA IS WELL-MADE , BUT IT'S JUST TOO DRY AN...
Name: review, Length: 5331, dtype: object

In [79]:
neg_rev.loc[:,'review'] = neg_rev.loc[:,'review'].apply(lambda x:x.lower())
neg_rev.loc[:,'review'] = neg_rev.loc[:,'review'].apply(lambda x:re.sub(r'@\S+','',x))
neg_rev.loc[:,'review'] = neg_rev.loc[:,'review'].apply(lambda x:x.translate(str.maketrans(dict.fromkeys((string.punctuation)))))
neg_rev.loc[:,'review'] = neg_rev.loc[:,'review'].apply(lambda x: " ".join([word for word in x.split() if word not in (sw)]))
neg_rev.loc[:,'review'] = neg_rev.loc[:,'review'].apply(lambda x:" ".join([lm.lemmatize(word,pos='v') for word in x.split()]))
neg_rev.loc[:,'review']

0                                simplistic silly tedious
1       laddish juvenile teenage boys could possibly f...
2       exploitative largely devoid depth sophisticati...
3       garbus discard potential pathological study ex...
4       visually flashy narratively opaque emotionally...
                              ...                        
5326         terrible movie people nevertheless find move
5327    many definitions time waster movie must surely...
5328    stand crocodile hunter hurry badly cobble look...
5329             thing look like madeforhomevideo quickie
5330                           enigma wellmade dry placid
Name: review, Length: 5331, dtype: object

In [80]:
com_rev = pd.concat([pos_rev,neg_rev],axis=0).reset_index()
com_rev

index                                             review  mood
0          0  rock destine 21st centurys new conan hes go ma...   1.0
1          1  gorgeously elaborate continuation lord ring tr...   1.0
2          2                          effective tootepid biopic   1.0
3          3  sometimes like go movies fun wasabi good place...   1.0
4          4  emerge something rare issue movie thats honest...   1.0
...      ...                                                ...   ...
10657   5326       terrible movie people nevertheless find move   0.0
10658   5327  many definitions time waster movie must surely...   0.0
10659   5328  stand crocodile hunter hurry badly cobble look...   0.0
10660   5329           thing look like madeforhomevideo quickie   0.0
10661   5330                         enigma wellmade dry placid   0.0

[10662 rows x 3 columns]

In [81]:
# Train Test Split
xtrain,xtest,ytrain,ytest = train_test_split\
(com_rev['review'].values,com_rev['mood'].values,random_state=40,test_size=0.2)
# xtrain

In [82]:
train_data = pd.DataFrame({'review':xtrain,'mood':ytrain})
test_data = pd.DataFrame({'review':xtest,'mood':ytest})


In [83]:
train_data

review  mood
0                                      enjoy hate later   1.0
1          remember kind movie hop ecks vs sever xxx go   1.0
2     spend screen series go star trek nemesis even ...   0.0
3     clutchy indulgent pretentious travelogue diatr...   0.0
4                         suffer flat script low budget   0.0
...                                                 ...   ...
8524  although try balance selfreferential humor nor...   0.0
8525  great fun sport aficionados ordinary louts who...   1.0
8526  isnt even movie enjoy mild escapism one fear f...   0.0
8527    dull mechanical kinda like goofy museum exhibit   0.0
8528  though bite patchwork script production glossy...   0.0

[8529 rows x 2 columns]

In [84]:
test_data

review  mood
0     salton sea moments inspire humour though every...   1.0
1     demented kitsch mess although smeary digital v...   1.0
2        one slyly exquisite antiadult movies ever make   1.0
3     come away wish though movie spend lot less tim...   0.0
4     ultimately feel empty unsatisfying like swallo...   1.0
...                                                 ...   ...
2128  maintain sympathy otherwise challenge soul let...   1.0
2129  meticulously uncover trail outrageous force cr...   1.0
2130     plot grow thin soon find pray quick resolution   0.0
2131  ingenuity parker display freshen play almost c...   1.0
2132  one greatest familyoriented fantasyadventure m...   1.0

[2133 rows x 2 columns]

In [85]:
# vectorizer = TfidfVectorizer()
# train_vectorizer = vectorizer.fit_transform(train_data['review'])
# test_vectorizer = vectorizer.transform(test_data['review'])

In [86]:
# test_vectorizer.toarray()

In [87]:
# train_vectorizer.toarray()

In [88]:
# from sklearn import svm
# from sklearn.metrics import classification_report

In [89]:
# classifier = svm.SVC(kernel='linear')
# classifier.fit(train_vectorizer,train_data['mood'])


In [90]:
# prediction = classifier.predict(test_vectorizer)
# prediction

In [91]:
# report = classification_report(test_data['mood'],prediction
# #                                ,output_dict=True
#                               )
# print(report)

In [92]:
# vectorizer_cnt = CountVectorizer()
# train_vectorizer = vectorizer.fit_transform(train_data['review'])
# test_vectorizer = vectorizer.transform(test_data['review'])

In [93]:
# from sklearn import svm
# from sklearn.metrics import classification_report

In [94]:
# classifier = svm.SVC(kernel='linear')
# classifier.fit(train_vectorizer,train_data['mood'])

In [95]:
# prediction = classifier.predict(test_vectorizer)
# prediction

In [96]:
# report = classification_report(test_data['mood'],prediction
# #                                ,output_dict=True
#                               )
# print(report)

In [97]:
vectorizer = TfidfVectorizer()
train_vectorizer = vectorizer.fit_transform(train_data['review'])
test_vectorizer = vectorizer.transform(test_data['review'])

In [98]:
train_vectorizer.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [99]:
ytrain

array([1., 1., 0., ..., 0., 0., 0.])

In [100]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report
classifier = GaussianNB()
classifier.fit(train_vectorizer.toarray(),ytrain)

GaussianNB()

In [101]:
predictions = classifier.predict(test_vectorizer.toarray())
predictions

array([1., 0., 0., ..., 1., 0., 1.])

In [102]:
report = classification_report(ytest,predictions)
print(report)

              precision    recall  f1-score   support

         0.0       0.72      0.62      0.66      1086
         1.0       0.65      0.75      0.70      1047

    accuracy                           0.68      2133
   macro avg       0.69      0.68      0.68      2133
weighted avg       0.69      0.68      0.68      2133



In [103]:
# a = input('write the review : ')
# vector = vectorizer.transform([a]).toarray()
# my_pred = classifier.predict(vector)
# print(my_pred)

In [104]:
import joblib
model_filename = 'Sentiment_Analysis_model.pkl'
vector_filename = 'Sentiment_vector.pkl'
joblib.dump(classifier,model_filename)
joblib.dump(vectorizer,vector_filename)

['Sentiment_vector.pkl']